### ISSUE TITLE
Google Play

### ISSUE THREAD

**Issue by SweetLion** [haha01haha01/HaRail_Android#1]
Hey, 
thank you very much for your awesome app. Is HaRail available on Google Play?

**Comment by hadeutscher** [comment]
Nope, why?

**Comment by SweetLion** [comment]
Perhaps you can reach more users on Google Play. But I can understand if you do not like the TOS from Google 😋

**Comment by hadeutscher** [comment]
No problem with the TOS, I just didn't get the time to bother with Play Store yet as I'm working on multiple projects atm and this one is not the highest priority.

**Comment by hadeutscher** [comment]
Available on GP

**Comment by SweetLion** [comment]
Very nice. Do you have got a link for me so that I can add a Google Play badge in the README? Thanks for your awesome work!

**Comment by hadeutscher** [comment]
sure, here it is: https://play.google.com/store/apps/details?id=com.haha01haha01.harail

Thanks for contributing :+1:
